services:

        shinobi-ubuntu-linux-desktop:

        container_name: shinobi-ubuntu-linux-desktop

        hostname: urus

        image: softwareshinobi/shinobi-ubuntu-linux-desktop:pristine

        restart: unless-stopped

        build: 

            context: .

            dockerfile: Dockerfile    

        ports:

            - "5922:22"

            - "5980:80"

            - "5900:5900"

        environment:
        
            TZ: America/Bogota

            USER_UID: 1000

            USER_GID: 1000

            USER: shinobi

            PASSWORD: shinobi

            HTTP_PASSWORD: shinobi
