services:

    shinobi-ubuntu-linux-desktop:

        container_name: shinobi-ubuntu-linux-desktop

        image: softwareshinobi/shinobi-ubuntu-linux-desktop:minimal

        restart: unless-stopped

        hostname: veneno

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - "5922:22"

            - "5980:80"

            - "5900:5900"

        environment:

            TZ: America/New_York

            USER_UID: 1000

            USER_GID: 1000

            USER: shinobi

            PASSWORD: shinobi

            HTTP_PASSWORD: shinobi
