services:

    shinobi-ubuntu-linux-desktop:

        container_name: shinobi-ubuntu-linux-desktop

        image: softwareshinobi/shinobi-ubuntu-linux-desktop:main

        restart: unless-stopped

        hostname: ${PROJECT_HOSTNAME}

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - "${PORT_SSH}:22"

            - "${PORT_WEB}:80"

            - "${PORT_VNC}:5900"

        environment:

            TZ: ${TIMEZONE}

            USER_UID: 1000

            USER_GID: 1000

            USER: ${VNC_USER}

            PASSWORD: ${VNC_PASSWORD}

            HTTP_PASSWORD: ${WEB_HTTP_PASSWORD}
